name: Terraform CICD Pipeline - ECS PROJECT

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Pipeline'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'eu-west-1'

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./terraform  

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::913513914993:role/OIDC_ROLE
        aws-region: ${{ env.AWS_REGION }}

    - name: 'Set up Terraform'
      uses: hashicorp/setup-terraform@v2

    - name: 'Set up TFLint'
      uses: terraform-linters/setup-tflint@v4

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Format'
      run: terraform fmt

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'TFLint'
      run: |
        tflint --init
        tflint

    - name: 'Run Tfsec'
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        additional_args: --minimum-severity HIGH

    - name: 'Terraform Plan'
      run: terraform plan -out=tfplan

    - name: 'Terraform Apply'
      run: terraform apply -auto-approve tfplan
